// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR1gcOLvBJ1ld9ER5-UbxAYifMxSfBKIU',
    appId: '1:737687514093:web:b96b0611bf5b6d9b3995e4',
    messagingSenderId: '737687514093',
    projectId: 'azume-try',
    authDomain: 'azume-try.firebaseapp.com',
    storageBucket: 'azume-try.appspot.com',
    measurementId: 'G-XTKBNW4TXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM_hcACcs0Ogc-JXWuoPJ5-ezlxv8_5no',
    appId: '1:737687514093:android:26ac440d5bbad1183995e4',
    messagingSenderId: '737687514093',
    projectId: 'azume-try',
    storageBucket: 'azume-try.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClUBfB6dxb9eKT66gxxeEYoq7oz0tEmEE',
    appId: '1:737687514093:ios:7d92034a07d497303995e4',
    messagingSenderId: '737687514093',
    projectId: 'azume-try',
    storageBucket: 'azume-try.appspot.com',
    iosBundleId: 'com.example.mentorupApp',
  );
}
